package jdbcdemo.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.domain.Person;

public class PersonRepository extends RepositoryBase<Person>{

	public PersonRepository(Connection connection, ResultSetMapper<Person> mapper) throws SQLException{
		super(connection, mapper);
	}

	@Override
	protected String selectAllSql() {
		return "SELECT * FROM person";
	}

	@Override
	protected String deleteSql() {
		return "DELETE FROM person WHERE id=?";
	}

	@Override
	protected String updateSql() {
		return "UPDATE person SET (name, surname, age) = (?,?,?) WHERE id=?";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO person(name,surname,age) VALUES (?,?,?)";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE person("
				+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "surname VARCHAR(50),"
				+ "age INT"
				+ ")";
	}

	@Override
	protected String tableName() {
		return "person";
	}

	@Override
	protected void setInsert(Person entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		insert.setInt(3, entity.getAge());
	}

	@Override
	protected void setUpdate(Person entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setInt(3, entity.getAge());
		update.setInt(4, entity.getId());
	}
}
